[versions]
# Kotlin
kotlin = "2.2.20"

# Logging
log4j = "2.25.4"
slf4j = "2.0.17"

# Configurate
configurate = "4.2.0"

# Plugins
shadow = "9.4.1"

# Other dependencies
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.8.1"
clikt = "5.0.3"
jnats = "2.25.2"
adventure = "5.0.1"
cloud-api = "0.1.0-platform.29-dev.1777216779595-3228d3d"
postgre = "42.7.11"
caffeine = "3.2.4"

# JOOQ
jooq = "3.21.3"

# Proto Buf
protobuf = "4.34.1"
grpc = "1.81.0"
grpc-kotlin = "1.5.0"

# Ktor
ktor = "3.2.2"

# Minecraft
velocity = "3.5.0-SNAPSHOT"
paper = "1.21.11-R0.1-SNAPSHOT"

[libraries]
# Kotlin
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Logging
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Configurate
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

# Other dependencies
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
postgre-jdbc = { module = "org.postgresql:postgresql", version.ref = "postgre" }
cloud-api = { module = "app.simplecloud.api:api", version.ref = "cloud-api" }

# Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }

# JOOQ
jooq = { module = "org.jooq:jooq-kotlin", version.ref = "jooq" }
jooq-meta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
jooq-meta-extensions = { module = "org.jooq:jooq-meta-extensions", version.ref = "jooq" }
jooq-kotlin-coroutines = { module = "org.jooq:jooq-kotlin-coroutines", version.ref = "jooq" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Proto Buf
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }

grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }

# Minecraft
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[bundles]
logging = ["log4j-core", "log4j-api", "log4j-slf4j-impl", "slf4j-api"]
adventure = ["adventure-text-serializer-gson", "adventure-api", "adventure-text-minimessage"]
configurate = ["configurate-yaml", "configurate-extra-kotlin"]
jooq = ["jooq-kotlin-coroutines", "jooq", "jooq-meta-extensions", "jooq-meta"]
ktor-server = ["ktor-serialization-kotlinx-json", "ktor-server-netty", "ktor-server-content-negotiation", "ktor-server-core", "ktor-server-cors", "ktor-server-websockets"]
grpc = ["grpc-stub", "grpc-netty-shaded", "grpc-kotlin-stub", "grpc-protobuf", "protobuf-kotlin"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
